language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=coala
    - python: 3.6
      env: TOXENV=docs
    - python: 3.6
      env: TOXENV=docs-linkcheck

sudo: false
cache: pip

install: pip install tox
script: tox
