language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=build
    - python: 3.6
      env: TOXENV=coala
    - python: 3.6
      env: TOXENV=linkcheck

sudo: false
cache: pip

install: pip install tox
script: tox
